version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "bookmarks"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"